FROM debian:bookworm as fluent

RUN apt update\
 && apt install -y --no-install-recommends\
 g++\
 make\
 cmake\
 ca-certificates\
 wget\
 flex\
 bison\
 libyaml-dev\
 libssl-dev\
 patch

# downlaod fluent-bit.
COPY OpenRTM-aist/scripts/bookworm/fluent-bit-4.0.3-ubuntu.patch /root/fluent-bit-4.0.3-ubuntu.patch
RUN mkdir /root/fluent-bit
RUN wget -O - https://github.com/fluent/fluent-bit/archive/refs/tags/v4.0.3.tar.gz\
 | tar xfz - -C /root/fluent-bit --strip-components 1\
 && patch -p1 -d /root/fluent-bit < /root/fluent-bit-4.0.3-ubuntu.patch
RUN sed  -i -e 's/jemalloc-5.3.0\/configure/jemalloc-5.3.0\/configure --disable-initial-exec-tls/g' /root/fluent-bit/CMakeLists.txt

# build fluent-bit.
RUN cmake -DFLB_TRACE=Off\
 -DFLB_EXAMPLES=Off\
 -DFLB_OUT_KAFKA=On\
 -DCMAKE_BUILD_TYPE=Release\
 -DCMAKE_INSTALL_PREFIX=/tmp/flb/install\
 -S /root/fluent-bit\
 -B/tmp/flb/build
RUN cmake --build /tmp/flb/build --target install/strip -- -j$(nproc)

# install header files.
RUN cp -r /root/fluent-bit/lib/msgpack-*/include/msgpack.h\
 /root/fluent-bit/lib/msgpack-*/include/msgpack\
 /root/fluent-bit/lib/cfl/include/cfl\
 /root/fluent-bit/lib/cfl/lib/xxhash/*.h\
 /root/fluent-bit/lib/cmetrics/include/cmetrics\
 /root/fluent-bit/lib/cmetrics/include/prometheus_remote_write\
 /root/fluent-bit/lib/ctraces/include/ctraces\
 /root/fluent-bit/lib/ctraces/lib/mpack/src/mpack\
 /root/fluent-bit/lib/cprofiles/include/cprofiles\
 /tmp/flb/install/include/
RUN cp /tmp/flb/build/lib/cprofiles/include/cprofiles/*.h\
 /tmp/flb/install/include/cprofiles/
RUN cp -r /root/fluent-bit/lib/monkey/include/monkey/mk_core/external\
 /tmp/flb/build/lib/monkey/include/monkey/mk_core/mk_core_info.h\
 /tmp/flb/install/include/monkey/mk_core/
RUN cp /root/fluent-bit/lib/monkey/include/monkey/*.h\
 /tmp/flb/build/lib/monkey/include/monkey/mk_info.h\
 /tmp/flb/install/include/monkey/
RUN mkdir -p /tmp/flb/install/deps/rbtree\
 && cp /root/fluent-bit/lib/monkey/deps/rbtree/rbtree.h\
 /tmp/flb/install/deps/rbtree/
RUN mkdir /tmp/flb/install/include/nghttp2\
 && cp /root/fluent-bit/lib/nghttp2*/lib/includes/nghttp2/nghttp2.h\
 /tmp/flb/build/lib/nghttp2*/lib/includes/nghttp2/nghttp2ver.h\
 /tmp/flb/install/include/nghttp2/

############################################################
FROM debian:bookworm as rtm-build

RUN apt update\
 && apt install -y --no-install-recommends\
 g++\
 make\
 cmake\
 uuid-dev\
 libboost-filesystem-dev\
 omniorb-nameserver\
 libomniorb4-dev\
 omniidl\
 && apt clean\
 && rm -rf /var/lib/apt/lists/*

COPY --from=fluent /tmp/flb/install /usr/local/
