name: OpenRTM on Linux

on:
  push:
  pull_request:
  workflow_dispatch:  

jobs:

  build:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu_2204, ubuntu_2404]
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Build ${{matrix.os}}
        run: docker build .. --file scripts/${{matrix.os}}/Dockerfile --tag openrtm:${{matrix.os}}

  code-analysis:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Code analysis 
        run: docker build .. --file scripts/code_analysis/Dockerfile --tag openrtm:code_analysis

